# Generated by Django 4.2.3 on 2023-07-14 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('CAMPO', 'campo')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='imagem/%Y/%m/%d/')),
                ('eh_publicada', models.BooleanField(default=False)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
