# Generated by Django 4.2.3 on 2023-07-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='categoria',
            field=models.CharField(choices=[('PESSOA', 'pessoa'), ('CONSOLE', 'console')], default='', max_length=100),
        ),
    ]
