# Generated by Django 4.2.3 on 2023-07-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagem_usuario_alter_imagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='eh_publicada',
            field=models.BooleanField(default=True),
        ),
    ]
